version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financial-dashboard-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - financial-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://giljurha01.cafe24.com/api
    container_name: financial-dashboard-frontend
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - financial-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: financial-dashboard-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
    networks:
      - financial-network
    restart: unless-stopped

networks:
  financial-network:
    driver: bridge

volumes:
  backend-data:
    driver: local