name: Deploy to Cafe24

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Backend Build
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    # Frontend Build
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Build frontend
      run: |
        cd frontend
        npm ci
        npm run build

    - name: Copy frontend to backend static resources
      run: |
        mkdir -p backend/src/main/resources/static
        cp -r frontend/build/* backend/src/main/resources/static/

    - name: Build integrated WAR file
      run: |
        cd backend
        chmod +x gradlew
        ./gradlew clean bootWar
        cp build/libs/backend-0.0.1-SNAPSHOT.war build/libs/ROOT.war

    # Deploy integrated WAR to Tomcat
    - name: Deploy WAR to Cafe24 Tomcat
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./backend/build/libs/
        server-dir: /webapps/
        dangerous-clean-slate: false

    # Restart Tomcat
    - name: Restart Tomcat via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd ~/bin
          ./shutdown.sh || true
          sleep 5
          ./startup.sh
